### ISSUE TITLE
nabu casa

### ISSUE THREAD

**Issue by riemers** [bradleyscott/home-automation#1]
Presume you know but your nabu casa url is showing. Not that people can enter, but every time a person tries like a default username and password you will get a notification that someone typed in a incorrect username/pwd.. and your location is still in the config.

i usually search for gems in the home assistant configs of people and when i bump into these things i usually report it.

**Comment by bradleyscott** [comment]
Yes, aware of that. Any suggestions about how to inject push notification click urls without the full domain name in the automation?

Also, have you seen another strategy for zone definition? I guess you could inject secrets for the late/long?

**Comment by riemers** [comment]
You can inject secrets for zones, but you can also just split the zones into a different file and put it in the .gitignore. I only want my home to be 'secret' the zones i don't care that much (work, shopping, horse driving) nobody wants to come there ;)

On the push notification link, depends on what device you have. If you have IOS you can make it in such a way that if you force press the event it will stream the camera. That way it doesn't need the url.

See https://www.home-assistant.io/docs/ecosystem/ios/notifications/content_extensions/

But i have a funny feeling your on android ;)
